### ISSUE TITLE
 Heatmap correlation for GSEA pathways

### ISSUE THREAD

**Issue by azwainCC** [hbc/Drosophila-immune-cell-populations-at-single-cell-transcriptome-resolution-paper#1]
Hello
Could you please post the code (not sure if I am missing to trace in the files) for below figure- Heatmap correlation generated for GSEA pathway analysis??
<img width="461" alt="image" src="https://github.com/hbc/A-single-cell-survey-of-Drosophila-blood/assets/113923186/2549462a-ada1-48d2-873a-7f9c5e17f799">

Thanks in Advance!
Az

**Comment by mjsteinbaugh** [comment]
Hi @azwainCC ,

Send Sudhir an email at [sudhir_gt@hms.harvard.edu](mailto:sudhir_gt@hms.harvard.edu). If I remember correctly, one of the Perrimon lab members generated this figure. 

Best,
Mike
