### ISSUE TITLE
add transgenes into the data

### ISSUE THREAD

**Issue by azwainCC** [hbc/Drosophila-immune-cell-populations-at-single-cell-transcriptome-resolution-paper#2]
Hello
Could you able to see transgenes expression(EGFP) in your single cell dataset or did you align with those sequence files having transgenes? I see the below code in your files, just checking how to add engineered foreign transgenes for my dataset. 
gffFile = file.path(
        "..",
        "annotations",
        "flybase",
        "FB2018_02",
        "dmel-all-r6.21-spike.gtf"
    ),
    transgeneNames = c("EGFP", "gal4")
)
Thanks in advance!
Az

**Comment by mjsteinbaugh** [comment]
Hi @azwainCC , thanks for getting in touch!

The way we did the analysis of the spike-in sequences, including EGFP, was to create a custom transcriptome for the project, which is documented here:
https://github.com/hbc/A-single-cell-survey-of-Drosophila-blood/blob/master/indrops/replicates/README

Basically we combined files from FlyBase with the additional sequences:

Transcriptome details:
FlyBase (FB2018_02 r6.21)
Assembled by combining:
- dmel-all-transcript-r6.21.fasta.gz
- dmel-all-miRNA-r6.21.fasta.gz
- dmel-all-miscRNA-r6.21.fasta.gz
- dmel-all-ncRNA-r6.21.fasta.gz
- dmel-all-pseudogene-r6.21.fasta.gz
- dmel-all-tRNA-r6.21.fasta.gz
- EGFP and GAL4 FASTA spike-ins

All fasta files (including the sequence for EGFP and GAL4) were concatenated to generate a single "complete" genome.  This genome was used for alignment for bcbio-nextgen.

And then to look into R with bcbioSingleCell, we set `transgeneNames` above as shown to note that these are custom sequences. But the counts themselves were generated first with bcbio-nextgen.

Happy to help with your analysis.

Best,
Mike

**Comment by azwainCC** [comment]
Hi @mjsteinbaugh 
Thanks a lot for your response. Could you able to do this (adding additional transgenes and checking expression) with 10X cellRanger files and there after the analysis in R as well?
Thanks
Az

**Comment by mjsteinbaugh** [comment]
If I remember correctly Cell Ranger supports spike-ins and custom sequences as well. You may have to create a custom file to make that work, but you should see read counts for the sequences of interest in the output MTX or HDF5 files.
